### ISSUE TITLE
Missing Consistency levels

### ISSUE THREAD

**Issue by kaushalshriyan** [jalkanen/cassandracalculator#6]
I am referring to http://cassandra.apache.org/doc/latest/architecture/dynamo.html?highlight=tunable%20consistency#tunable-consistency.

The following consistency levels are not described in https://www.ecyrd.com/cassandracalculator/

LOCAL_QUORUM
A majority of the replicas in the local datacenter (whichever datacenter the coordinator is in) must respond.
EACH_QUORUM
A majority of the replicas in each datacenter must respond.
LOCAL_ONE
Only a single replica must respond. In a multi-datacenter cluster, this also gaurantees that read requests are not sent to replicas in a remote datacenter.
ANY
A single replica may respond, or the coordinator may store a hint. If a hint is stored, the coordinator will later attempt to replay the hint and deliver the mutation to the replicas. This consistency level is only accepted for write operations.

Please comment further.

**Comment by shriyankaushal** [comment]
@jalkanen I will appreciate if you can take a look at the issue which i posted here

**Comment by kaushalshriyan** [comment]
@jalkanen I will appreciate if you can take a look at the issue which i posted here

**Comment by shriyankaushal** [comment]
@jalkanen  I will appreciate if you can take a look at the issue which i posted here

**Comment by shriyankaushal** [comment]
@jalkanen I will appreciate if you can take a look at the issue which i posted here

**Comment by jalkanen** [comment]
Hi!

Multi-DC configurations aren't supported, as they get complicated to visualize. If someone can figure out a good way how to do that, I'll gladly accept a PR. But for now multi-DC is off the list.
